<!doctype html>
<html lang="es"><head><meta charset="utf-8"><style>
body{font-family:DejaVu Sans,sans-serif;font-size:8px;color:#25324b}h1{font-size:17px;margin:0 0 4px}.muted{color:#667085}.cards{width:100%;margin:14px 0}.cards td{border:1px solid #d8dee9;padding:8px}.value{font-size:13px;font-weight:bold}table.detail{width:100%;border-collapse:collapse}.detail th,.detail td{border:1px solid #d8dee9;padding:4px}.detail th{background:#eef2f7;text-align:left}.right{text-align:right}.danger{color:#b42318}.success{color:#067647}
</style></head><body>
<h1>Seguimiento de Agencia</h1>
<div class="muted">Período cerrado: {{ $fechaInicio->format('d/m/Y') }} al {{ $fechaFin->format('d/m/Y') }} · {{ $dias_analizados }} días · Generado {{ now()->format('d/m/Y H:i') }}</div>
<table class="cards"><tr><td>Agencias<div class="value">{{ $resumen['agencias'] }}</div></td><td>Meta acumulada<div class="value">RD$ {{ number_format($resumen['meta_acumulada'], 2) }}</div></td><td>Venta<div class="value">RD$ {{ number_format($resumen['venta'], 2) }}</div></td><td>Cumplimiento<div class="value">{{ number_format($resumen['cumplimiento'], 1) }}%</div></td><td>Brecha<div class="value {{ $resumen['brecha'] >= 0 ? 'success' : 'danger' }}">RD$ {{ number_format($resumen['brecha'], 2) }}</div></td></tr></table>
<table class="detail"><thead><tr><th>Empresa</th><th>Ciudad</th><th>Coordinador</th><th>Ruta</th><th>Agencia</th><th>Producto</th><th>Meta</th><th>Venta</th><th>%</th><th>Brecha</th><th>Días ✓/✕</th><th>Estado</th></tr></thead><tbody>
@foreach ($filas as $fila)<tr><td>{{ $fila['empresa'] }}</td><td>{{ $fila['ciudad'] }}</td><td>{{ $fila['coordinador'] }}</td><td>{{ $fila['ruta'] }}</td><td>{{ $fila['agencia'] }}<br><span class="muted">{{ $fila['terminal'] }}</span></td><td>{{ $fila['producto'] }}</td><td class="right">{{ number_format($fila['meta_acumulada'], 2) }}</td><td class="right">{{ number_format($fila['venta'], 2) }}</td><td class="right">{{ number_format($fila['cumplimiento'], 1) }}%</td><td class="right {{ $fila['brecha'] >= 0 ? 'success' : 'danger' }}">{{ number_format($fila['brecha'], 2) }}</td><td class="right">{{ $fila['dias_cumplidos'] }}/{{ $fila['dias_no_cumplidos'] }}</td><td>{{ $fila['estado'] }}</td></tr>@endforeach
</tbody></table></body></html>
