INSERT INTO incentivo_administrativos (grupo, nombre, empresa, pct_total, created_at, updated_at)
VALUES
('1. Gtes. Y Encarg.', 'Aramis Morel Arroyo', 'Consorcio Joselito', 6.00, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Yulaine Echevarria', 'Consorcio Joselito', 3.50, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Johanset Batista', 'Consorcio Joselito', 3.00, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Ciprian Rafael Beard Almonte', 'Consorcio Joselito', 3.00, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Renzo Figueroa', 'Consorcio Joselito', 2.00, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Erick junior Velasquez gomez', 'Negosur', 5.50, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Altagracia karina Vallejo Bueno', 'Negosur', 2.00, NOW(), NOW()),
('1. Gtes. Y Encarg.', 'Harlin Cerda Cerda', 'Consorcio Joselito', 2.00, NOW(), NOW()),
('2. Monitoreo', 'Geldhis Paola Acosta Carrion', 'Consorcio Joselito', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Joselania Olivo García', 'Consorcio Joselito', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Kengripher Junior De Oleo Belen', 'Consorcio Joselito', 1.30, NOW(), NOW()),
('2. Monitoreo', 'María Liriano', 'Consorcio Joselito', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Stefanny Onasi Webster', 'Consorcio Joselito', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Reidy Reynoso Melendez', 'Consorcio Joselito', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Leyshi Y. Beras', 'Negosur', 1.30, NOW(), NOW()),
('2. Monitoreo', 'yolaidi Arias', 'Negosur', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Hector De Regla Mariñez Diaz', 'Negosur', 1.30, NOW(), NOW()),
('2. Monitoreo', 'Sherlyn Lexander Perdomo valdez', 'Negosur', 1.30, NOW(), NOW()),
('4. Operadores', 'Sayi Virginia Marmolejos', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Lenny Suero Ogando', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Dairy Perez vasquez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'LUIS JAVIER MARTINEZ', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Richard Guzman Herrera', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Armandalis Baez Cuevas', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Erick Payano', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Pedro Minier', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Valentin Mieses', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Jonathan Peralta', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Gabriel Martinez De Jesus (2 meses)', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Juan Luis Montaño', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Wilmer Jose Corporán Colon', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Santo Tibrey Rosario (1 mes)', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Hector Manuel Medina', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Jose Luis Rodriguez', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Juan Geronimo Garcia', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Alexander Cepeda', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Juan Francisco Mejía', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Victor Manuel de la Cruz', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Sterling Miguel Bello Bello', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Starlin Arredondo Martinez', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Santico Julian Willian Fenelon', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Wilkin Cabral', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Rosmery Celeste Nú ñ ez naranjo', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Osvaldo Antonio Moreno Perez', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('4. Operadores', 'Leydi Guerrero', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Alba Yris Tapia Morillo', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Yenifer Estefani Baez Cordero', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Yudekis Tejeda Tejeda', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Hector Guerrero Tejeda', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Sandra Diomare Arias Garcia', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Yaniris Reynoso', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'jerry alejandro anziani arias', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Victor Baez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Carla yasmel Barias baez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Estafani Espinosa', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'FElix Rosario', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Rosabel Arias de Lara', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Alex Yadir Figuereo Abreu', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Rafaela Brito', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Samir Ferrera', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Martin alejandro fernandez bello', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Victor julio Galvan montero', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Raulin Matos', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Nestor Antonio Terrero', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Leivin Pina Feliz', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Jeison Manuel Feliz Feliz', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'José vega', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Georges gabriel reyes cuevas', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'yeandrys dileissy Ortiz perez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Silvia patricia batista diaz', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Fermin brito De leon', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Manuel Emilio Pérez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Manuel Emilio Rivas', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Marco daniel Méndez gonzalez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'waner omar diaz sena', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Zenaldo gregorio volquez perez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Wilton feliz Alcantara pienda', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Deibi Garcia Made', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Pedro Suero', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Martires Suero Flores', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Melvin Moreno', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Juan gonzalez', 'Negosur', 0.70, NOW(), NOW()),
('4. Operadores', 'Jael Rosario Antigua', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Bryan Jose Rodriguez de Jesus', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Juan Francisco De La Cruz Aracena', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Brian Oriel Robles Tolentino', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Daniel Matos Gomez', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Dymitri Joseph', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Isidro Valdez Pascual', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Rudys Bernardo Cabrera', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Socrates Osiris Morban Piña', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Jose Antonio De Peña De La Cruz', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Juan Perez Desena', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Jose Antonio Polanco Vasquez', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Josué Johan Martinez Mancebo', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Pedro Hector Santana Mateo', 'Consorcio Joselito', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Julio Inocencio Dominguez Perez', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Raulin Guerrero', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Comas Abreu Marcos', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Wendi Reyes', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Henry Matos', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Ignacio Nivar Victoriano', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'LUIS ENRIQUE MERAN MORA', 'Negosur', 0.70, NOW(), NOW()),
('5. Servs. Tecnicos', 'Angel luis Rivera Carvajal', 'Negosur', 0.70, NOW(), NOW())
ON DUPLICATE KEY UPDATE pct_total = VALUES(pct_total), updated_at = VALUES(updated_at);
