# BUILD-MARKER-2026-04-14
server {
  listen 80;
  server_name _;
  root /var/www/public;
  index index.php;
  client_max_body_size 100m;

  location / {
    try_files $uri $uri/ /index.php?$query_string;
  }

  location ^~ /storage/ {
    alias /var/www/storage/app/public/;
    try_files $request_filename =404;
    access_log off;
    expires max;
  }

  location ~ \.php$ {
    include fastcgi_params;
    fastcgi_pass pruebacrm-crm-5dx2tv:9000;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_index index.php;
    fastcgi_connect_timeout 60s;
    fastcgi_send_timeout 600s;
    fastcgi_read_timeout 600s;
  }

  location ~ /\.ht {
    deny all;
  }
}