<?php

return [
    'dashboard' => [
        'titulo' => 'Dashboard',
        'breadcrumb' => 'Dashboard',
        'items' => [
            [
                'nombre' => 'Tablero Principal',
                'descripcion' => 'Consulta indicadores claves, ventas por tipo, agencias y balance mensual.',
                'url' => '/',
                'icono' => 'ri-dashboard-line',
                'categoria' => 'Principal',
                'tags' => ['inicio', 'tablero', 'indicadores', 'ventas'],
                'activo' => true,
            ],
            [
                'nombre' => 'Lotobet Ventas',
                'descripcion' => 'Dashboard financiero de LotoBet con ventas por tipo de producto y agencia.',
                'url' => '/ventas-lotobet-dashboard',
                'icono' => 'ri-bar-chart-box-line',
                'categoria' => 'Ventas',
                'tags' => ['lotobet', 'ventas', 'financiero'],
                'activo' => true,
            ],
            [
                'nombre' => 'KPI Metas',
                'descripcion' => 'Seguimiento de metas, cumplimiento y severidad para Lotobet.',
                'url' => '/kpi-lotobet',
                'icono' => 'ri-speed-up-line',
                'categoria' => 'Indicadores',
                'tags' => ['kpi', 'metas', 'lotobet'],
                'activo' => true,
            ],
            [
                'nombre' => 'Lotobet Flash',
                'descripcion' => 'Dashboard de ventas flash de LotoBet con lectura operativa por fecha.',
                'url' => '/ventas-lotobet-flash-dashboard',
                'icono' => 'ri-flashlight-line',
                'categoria' => 'Ventas',
                'tags' => ['lotobet', 'flash', 'ventas'],
                'activo' => true,
            ],
            [
                'nombre' => 'Lotonet Ventas',
                'descripcion' => 'Dashboard financiero de LotoNet con ventas por tipo de producto y agencia.',
                'url' => '/ventas-lotonet-dashboard',
                'icono' => 'ri-line-chart-line',
                'categoria' => 'Ventas',
                'tags' => ['lotonet', 'ventas', 'financiero'],
                'activo' => true,
            ],
            [
                'nombre' => 'Mar Ventas',
                'descripcion' => 'Dashboard de ventas MAR con filtros por periodo y lectura por agencia.',
                'url' => '/ventas-mar-dashboard',
                'icono' => 'ri-water-flash-line',
                'categoria' => 'Ventas',
                'tags' => ['mar', 'ventas', 'dashboard'],
                'activo' => true,
            ],
        ],
    ],

    'comercial' => [
        'titulo' => 'Comercial',
        'breadcrumb' => 'Comercial',
        'items' => [
            [
                'nombre' => 'Resumen Comercial',
                'descripcion' => 'Consulta acumulados comerciales de ventas tradicionales, no tradicionales y recargas.',
                'url' => '/comercial/resumen',
                'icono' => 'ri-dashboard-line',
                'categoria' => 'Resumen',
                'tags' => ['comercial', 'resumen', 'acumulados', 'ventas'],
                'activo' => true,
            ],
            [
                'nombre' => 'KPI Ventas',
                'descripcion' => 'Mide cumplimiento, metas y ventas mensuales por tipo de producto.',
                'url' => '/comercial/kpi-ventas',
                'icono' => 'ri-line-chart-line',
                'categoria' => 'Indicadores',
                'tags' => ['kpi', 'ventas', 'metas', 'mensual'],
                'activo' => true,
            ],
            [
                'nombre' => 'KPI Ventas V',
                'descripcion' => 'Vista alternativa de indicadores comerciales y seguimiento de ventas.',
                'url' => '/comercial/kpi-ventas-v',
                'icono' => 'ri-bar-chart-2-line',
                'categoria' => 'Indicadores',
                'tags' => ['kpi', 'ventas', 'comercial'],
                'activo' => true,
            ],
            [
                'nombre' => 'Plan de Agencias',
                'descripcion' => 'Gestiona planes comerciales por agencia y seguimiento de objetivos.',
                'url' => '/comercial/agencia-plan',
                'icono' => 'ri-store-2-line',
                'categoria' => 'Agencias',
                'tags' => ['agencias', 'plan', 'objetivos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Meta Incentivo',
                'descripcion' => 'Administra metas e incentivos del area comercial.',
                'url' => '/comercial/meta-incentivo',
                'icono' => 'ri-award-line',
                'categoria' => 'Incentivos',
                'tags' => ['metas', 'incentivo', 'comercial'],
                'activo' => true,
            ],
            [
                'nombre' => 'Ventas por Producto',
                'descripcion' => 'Analiza ventas comerciales agrupadas por producto.',
                'url' => '/comercial/ventas-producto',
                'icono' => 'ri-shopping-bag-3-line',
                'categoria' => 'Ventas',
                'tags' => ['ventas', 'producto', 'comercial'],
                'activo' => true,
            ],
        ],
    ],

    'contabilidad' => [
        'titulo' => 'Contabilidad',
        'breadcrumb' => 'Contabilidad',
        'items' => [
            [
                'nombre' => 'Inicio Contable',
                'descripcion' => 'Panel base de cuentas y utilidades generales de contabilidad.',
                'url' => '/contabilidad/inicio',
                'icono' => 'ri-bank-card-line',
                'categoria' => 'Gestion',
                'tags' => ['contabilidad', 'inicio', 'cuentas'],
                'activo' => true,
            ],
            [
                'nombre' => 'Comisiones',
                'descripcion' => 'Reporte y seguimiento de comisiones por periodo.',
                'url' => '/contabilidad/reportes/comisiones',
                'icono' => 'ri-percent-line',
                'categoria' => 'Reportes',
                'tags' => ['comisiones', 'reportes', 'contabilidad'],
                'activo' => true,
            ],
            [
                'nombre' => 'Estado de Resultado',
                'descripcion' => 'Consulta ingresos, gastos y resultados financieros.',
                'url' => '/contabilidad/reportes/estado-resultado',
                'icono' => 'ri-file-chart-line',
                'categoria' => 'Reportes',
                'tags' => ['estado resultado', 'finanzas', 'reportes'],
                'activo' => true,
            ],
            [
                'nombre' => 'Flujo de Ruta',
                'descripcion' => 'Analiza movimientos y flujo financiero por ruta.',
                'url' => '/contabilidad/reportes/flujo-ruta',
                'icono' => 'ri-route-line',
                'categoria' => 'Reportes',
                'tags' => ['flujo', 'ruta', 'contabilidad'],
                'activo' => true,
            ],
            [
                'nombre' => 'Electricidad',
                'descripcion' => 'Gestiona facturas, averias y seguimiento electrico de agencias.',
                'url' => '/contabilidad/electricidad',
                'icono' => 'ri-flashlight-line',
                'categoria' => 'Servicios',
                'tags' => ['electricidad', 'servicios', 'averias'],
                'activo' => true,
            ],
            [
                'nombre' => 'Centro de Costo',
                'descripcion' => 'Sincroniza y administra centros de costo contables.',
                'url' => '/contabilidad/centro-costo',
                'icono' => 'ri-node-tree',
                'categoria' => 'Gestion',
                'tags' => ['centro costo', 'sincronizar', 'contabilidad'],
                'activo' => true,
            ],
        ],
    ],

    'operaciones' => [
        'titulo' => 'Operaciones',
        'breadcrumb' => 'Operaciones',
        'items' => [
            [
                'nombre' => 'Panel Operativo',
                'descripcion' => 'Vista base para indicadores y seguimiento operativo.',
                'url' => '/operaciones/panel',
                'icono' => 'ri-dashboard-2-line',
                'categoria' => 'Gestion',
                'tags' => ['panel', 'operaciones', 'indicadores'],
                'activo' => true,
            ],
            [
                'nombre' => 'Gestion Operativa',
                'descripcion' => 'Administra actividades y seguimiento de operaciones.',
                'url' => '/operaciones/gestion',
                'icono' => 'ri-settings-3-line',
                'categoria' => 'Gestion',
                'tags' => ['gestion', 'operaciones'],
                'activo' => true,
            ],
            [
                'nombre' => 'Operador Ruta',
                'descripcion' => 'Relaciona operadores con rutas y agencias asignadas.',
                'url' => '/operaciones/operador-ruta',
                'icono' => 'ri-user-location-line',
                'categoria' => 'Rutas',
                'tags' => ['operador', 'ruta', 'agencias'],
                'activo' => true,
            ],
            [
                'nombre' => 'Rutas',
                'descripcion' => 'Gestiona rutas operativas y sus agencias asociadas.',
                'url' => '/operaciones/ruta',
                'icono' => 'ri-route-line',
                'categoria' => 'Rutas',
                'tags' => ['rutas', 'agencias', 'operaciones'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte Diario',
                'descripcion' => 'Procesa informes diarios, comprobantes, bancos y gastos.',
                'url' => '/operaciones/reportes/diario',
                'icono' => 'ri-calendar-check-line',
                'categoria' => 'Reportes',
                'tags' => ['reporte', 'diario', 'comprobantes'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte Mensual',
                'descripcion' => 'Consulta reportes operativos consolidados por mes.',
                'url' => '/operaciones/reportes/mensual',
                'icono' => 'ri-calendar-2-line',
                'categoria' => 'Reportes',
                'tags' => ['reporte', 'mensual', 'operaciones'],
                'activo' => true,
            ],
        ],
    ],

    'mantenimiento' => [
        'titulo' => 'Mantenimiento',
        'breadcrumb' => 'Mantenimiento',
        'items' => [
            [
                'nombre' => 'Agencias',
                'descripcion' => 'Administra agencias, terminales, estatus y datos operativos.',
                'url' => '/agencias',
                'icono' => 'ri-store-2-line',
                'categoria' => 'Agencias',
                'tags' => ['agencias', 'terminales', 'mantenimiento'],
                'activo' => true,
            ],
            [
                'nombre' => 'Incumplimientos Horario',
                'descripcion' => 'Da seguimiento a incumplimientos y asistencia por horario.',
                'url' => '/agencias-incumplimientos-horario',
                'icono' => 'ri-time-line',
                'categoria' => 'Agencias',
                'tags' => ['incumplimientos', 'horario', 'agencias'],
                'activo' => true,
            ],
            [
                'nombre' => 'Asistencia Comparativa',
                'descripcion' => 'Compara asistencia y marcas entre fuentes de datos.',
                'url' => '/agencias/asistencia-comparativa',
                'icono' => 'ri-file-list-3-line',
                'categoria' => 'Agencias',
                'tags' => ['asistencia', 'comparativa', 'agencias'],
                'activo' => true,
            ],
            [
                'nombre' => 'Catalogo de Juegos',
                'descripcion' => 'Administra productos y catalogo de juegos del sistema.',
                'url' => '/mantenimiento/catalogo-juegos',
                'icono' => 'ri-gamepad-line',
                'categoria' => 'Catalogos',
                'tags' => ['catalogo', 'juegos', 'productos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Usuarios',
                'descripcion' => 'Gestiona usuarios de acceso al CRM.',
                'url' => '/usuarios',
                'icono' => 'ri-user-settings-line',
                'categoria' => 'Seguridad',
                'tags' => ['usuarios', 'seguridad', 'accesos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Coordinador',
                'descripcion' => 'Administra coordinadores, operadores y asignaciones.',
                'url' => '/coordinador-operador',
                'icono' => 'ri-group-line',
                'categoria' => 'Operadores',
                'tags' => ['coordinador', 'operador', 'agencias'],
                'activo' => true,
            ],
            [
                'nombre' => 'Roles',
                'descripcion' => 'Gestiona roles de seguridad y permisos asociados.',
                'url' => '/roles',
                'icono' => 'ri-shield-user-line',
                'categoria' => 'Seguridad',
                'tags' => ['roles', 'seguridad', 'permisos'],
                'permission' => 'roles.view',
                'activo' => true,
            ],
            [
                'nombre' => 'Permisos',
                'descripcion' => 'Administra permisos disponibles en el sistema.',
                'url' => '/permissions',
                'icono' => 'ri-lock-password-line',
                'categoria' => 'Seguridad',
                'tags' => ['permisos', 'seguridad'],
                'permission' => 'permissions.view',
                'activo' => true,
            ],
            [
                'nombre' => 'Sesiones de Usuarios',
                'descripcion' => 'Revisa sesiones activas y auditoria de acceso de usuarios.',
                'url' => '/superadmin/sesiones',
                'icono' => 'ri-user-shared-line',
                'categoria' => 'Seguridad',
                'tags' => ['sesiones', 'usuarios', 'superadmin'],
                'role' => 'superadmin',
                'activo' => true,
            ],
        ],
    ],

    'tecnologia' => [
        'titulo' => 'Tecnologia',
        'breadcrumb' => 'Tecnologia',
        'items' => [
            [
                'nombre' => 'Solicitudes',
                'descripcion' => 'Registra y da seguimiento a solicitudes del area de tecnologia.',
                'url' => '/tecnologia/solicitudes',
                'icono' => 'ri-customer-service-2-line',
                'categoria' => 'Soporte',
                'tags' => ['tecnologia', 'solicitudes', 'soporte'],
                'activo' => true,
            ],
        ],
    ],

    'servicios_generales' => [
        'titulo' => 'Servicios Generales',
        'breadcrumb' => 'Servicios Generales',
        'items' => [
            [
                'nombre' => 'Requerimientos',
                'descripcion' => 'Registra tickets para los tecnicos: internet, electricidad, sistema frizado o cambio de inversor.',
                'url' => '/servicios-generales/requerimientos',
                'icono' => 'ri-tools-line',
                'categoria' => 'Soporte',
                'tags' => ['servicios generales', 'requerimientos', 'tecnicos', 'mantenimiento', 'inversor', 'internet', 'luz'],
                'permission' => 'servicios_generales.view',
                'activo' => true,
            ],
        ],
    ],

    'incentivos' => [
        'titulo' => 'Incentivos',
        'breadcrumb' => 'Incentivos',
        'items' => [
            [
                'nombre' => 'Procesar Incentivos',
                'descripcion' => 'Procesa incentivos por planes, efectividad y pagos.',
                'url' => '/incentivos/procesar',
                'icono' => 'ri-play-list-add-line',
                'categoria' => 'Procesos',
                'tags' => ['procesar', 'incentivos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Gestion Incentivos',
                'descripcion' => 'Administra la configuracion y registros de incentivos.',
                'url' => '/incentivos/gestion',
                'icono' => 'ri-award-line',
                'categoria' => 'Gestion',
                'tags' => ['gestion', 'incentivos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Incentivos Empleados',
                'descripcion' => 'Configura datos de empleados para calculos de incentivos.',
                'url' => '/incentivos/empleados',
                'icono' => 'ri-team-line',
                'categoria' => 'Empleados',
                'tags' => ['empleados', 'incentivos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte de Pagos',
                'descripcion' => 'Consulta pagos de incentivos realizados o pendientes.',
                'url' => '/incentivos/reporte-pagos',
                'icono' => 'ri-money-dollar-circle-line',
                'categoria' => 'Reportes',
                'tags' => ['pagos', 'reportes', 'incentivos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte Nuevo Incentivo',
                'descripcion' => 'Vista de reporte para el nuevo esquema de incentivos.',
                'url' => '/incentivos/reporte-nuevo-incentivo-view',
                'icono' => 'ri-file-chart-line',
                'categoria' => 'Reportes',
                'tags' => ['reporte', 'nuevo incentivo'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte Nuevo Incentivo V2',
                'descripcion' => 'Segunda version del reporte de incentivos.',
                'url' => '/incentivos/reporte-nuevo-incentivo-v2-view',
                'icono' => 'ri-file-copy-2-line',
                'categoria' => 'Reportes',
                'tags' => ['reporte', 'nuevo incentivo', 'v2'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte Nuevo Incentivo V3',
                'descripcion' => 'Tercera version del reporte de incentivos con pagos 60, 70 y 80.',
                'url' => '/incentivos/reporte-nuevo-incentivo-v3-view',
                'icono' => 'ri-file-list-3-line',
                'categoria' => 'Reportes',
                'tags' => ['reporte', 'nuevo incentivo', 'v3', 'pagos 60', 'pagos 70', 'pagos 80'],
                'activo' => true,
            ],
            [
                'nombre' => 'Reporte Nuevo Incentivo V4',
                'descripcion' => 'Cuarta version del reporte de incentivos con filtros por categoria en administrativo.',
                'url' => '/incentivos/reporte-nuevo-incentivo-v4-view',
                'icono' => 'ri-file-copy-line',
                'categoria' => 'Reportes',
                'tags' => ['reporte', 'nuevo incentivo', 'v4', 'administrativo', 'operadores'],
                'activo' => true,
            ],
            [
                'nombre' => 'Incentivo Administrativo',
                'descripcion' => 'Administra empleados base para distribucion administrativa.',
                'url' => '/incentivos/incentivo-administrativo',
                'icono' => 'ri-team-line',
                'categoria' => 'Configuracion',
                'tags' => ['crud', 'incentivo administrativo', 'grupo', 'porcentaje'],
                'activo' => true,
            ],
            [
                'nombre' => 'Porcentaje Incentivo',
                'descripcion' => 'Administra posiciones y bono porcentual del incentivo.',
                'url' => '/incentivos/porcentaje-incentivo',
                'icono' => 'ri-percent-line',
                'categoria' => 'Configuracion',
                'tags' => ['crud', 'porcentaje incentivo', 'bono', 'posicion'],
                'activo' => true,
            ],
        ],
    ],

    'procesos' => [
        'titulo' => 'Procesos',
        'breadcrumb' => 'Procesos',
        'items' => [
            [
                'nombre' => 'Gerencia',
                'descripcion' => 'Protocolos y procesos del departamento de gerencia.',
                'url' => '/procesos/gerencia',
                'icono' => 'ri-briefcase-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'gerencia'],
                'activo' => true,
            ],
            [
                'nombre' => 'Contabilidad',
                'descripcion' => 'Protocolos y procesos del departamento de contabilidad.',
                'url' => '/procesos/contabilidad',
                'icono' => 'ri-bank-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'contabilidad'],
                'activo' => true,
            ],
            [
                'nombre' => 'Recursos Humanos',
                'descripcion' => 'Protocolos y procesos de talento humano.',
                'url' => '/procesos/recursos-humanos',
                'icono' => 'ri-team-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'recursos humanos'],
                'activo' => true,
            ],
            [
                'nombre' => 'Operaciones',
                'descripcion' => 'Protocolos y procesos del departamento de operaciones.',
                'url' => '/procesos/operaciones',
                'icono' => 'ri-settings-3-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'operaciones'],
                'activo' => true,
            ],
            [
                'nombre' => 'Comercial',
                'descripcion' => 'Protocolos y procesos del departamento comercial.',
                'url' => '/procesos/comercial',
                'icono' => 'ri-line-chart-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'comercial'],
                'activo' => true,
            ],
            [
                'nombre' => 'Mantenimiento',
                'descripcion' => 'Protocolos y procesos del departamento de mantenimiento.',
                'url' => '/procesos/mantenimiento',
                'icono' => 'ri-tools-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'mantenimiento'],
                'activo' => true,
            ],
            [
                'nombre' => 'Tecnologia',
                'descripcion' => 'Protocolos y procesos del departamento de tecnologia.',
                'url' => '/procesos/tecnologia',
                'icono' => 'ri-computer-line',
                'categoria' => 'Departamentos',
                'tags' => ['procesos', 'tecnologia'],
                'activo' => true,
            ],
        ],
    ],

    'gerencia' => [
        'titulo' => 'Gerencia',
        'breadcrumb' => 'Gerencia',
        'items' => [
            [
                'nombre' => 'Gerencial',
                'descripcion' => 'Panel gerencial con indicadores y lectura ejecutiva del negocio.',
                'url' => '/gerencia/gerencial',
                'icono' => 'ri-dashboard-3-line',
                'categoria' => 'Indicadores',
                'tags' => ['gerencia', 'indicadores', 'ejecutivo'],
                'activo' => true,
            ],
            [
                'nombre' => 'Venta Gerencial',
                'descripcion' => 'Consulta ventas gerenciales con filtros y exportacion.',
                'url' => '/gerencia/venta-gerencial',
                'icono' => 'ri-line-chart-line',
                'categoria' => 'Ventas',
                'tags' => ['ventas', 'gerencial', 'exportacion'],
                'activo' => true,
            ],
            [
                'nombre' => 'Venta Comparativa',
                'descripcion' => 'Compara ventas entre periodos para analisis gerencial.',
                'url' => '/gerencia/venta-comparativa',
                'icono' => 'ri-bar-chart-grouped-line',
                'categoria' => 'Ventas',
                'tags' => ['ventas', 'comparativa', 'periodos'],
                'activo' => true,
            ],
        ],
    ],
];
