<?php

return [
    [
        'nombre' => 'Solicitudes de Empleo',
        'descripcion' => 'Gestiona solicitudes, formularios y expedientes de candidatos.',
        'url' => '/registro-empleados',
        'icono' => 'ri-file-user-line',
        'categoria' => 'Reclutamiento',
        'tags' => ['solicitudes', 'registro', 'candidatos', 'empleo'],
        'activo' => true,
    ],
    [
        'nombre' => 'Empleados',
        'descripcion' => 'Consulta empleados, estatus, dashboard y masa salarial por empresa.',
        'url' => '/empleados',
        'icono' => 'ri-team-line',
        'categoria' => 'Personal',
        'tags' => ['empleados', 'dashboard', 'estatus', 'salarios'],
        'activo' => true,
    ],
    [
        'nombre' => 'Novedades de Horario',
        'descripcion' => 'Revisa novedades, marcas y variaciones de horario del personal.',
        'url' => '/recursos-humanos/novedades-horario',
        'icono' => 'ri-time-line',
        'categoria' => 'Asistencia',
        'tags' => ['horario', 'novedades', 'asistencia', 'marcas'],
        'activo' => true,
    ],
    [
        'nombre' => 'Seguimiento Cruce de Usuarios',
        'descripcion' => 'Gestiona los casos generados desde el reporte de cruce de usuarios.',
        'url' => '/recursos-humanos/seguimiento-cruce-usuarios',
        'icono' => 'ri-user-search-line',
        'categoria' => 'Seguimiento',
        'tags' => ['recursos humanos', 'cruce usuarios', 'seguimiento', 'reportes'],
        'activo' => true,
    ],
    [
        'nombre' => 'Validador de Incentivos',
        'descripcion' => 'Valida por periodo quienes fueron pagados y los motivos de incentivos retenidos.',
        'url' => '/recursos-humanos/validador-incentivos',
        'icono' => 'ri-shield-check-line',
        'categoria' => 'Control',
        'tags' => ['incentivos', 'pagados', 'no pagados', 'cedulas', 'validacion'],
        'activo' => true,
    ],
    [
        'nombre' => 'Agencias Cerradas Domingos',
        'descripcion' => 'Identifica agencias activas sin ventas ni ponches en un domingo específico.',
        'url' => '/recursos-humanos/agencias-cerradas-domingos',
        'icono' => 'ri-store-2-line',
        'categoria' => 'Control',
        'tags' => ['agencias', 'cerradas', 'domingos', 'ventas', 'ponches'],
        'activo' => true,
    ],
    [
        'nombre' => 'Entrevista Online',
        'descripcion' => 'Registra entrevistas telefonicas u online realizadas a candidatos.',
        'url' => '/entrevistas-online',
        'icono' => 'ri-video-chat-line',
        'categoria' => 'Reclutamiento',
        'tags' => ['entrevista', 'candidatos', 'vacantes', 'online'],
        'activo' => true,
    ],
    [
        'nombre' => 'Empleados No Regularizados',
        'descripcion' => 'Da seguimiento a empleados pendientes de regularizacion.',
        'url' => '/empleados-no-regularizados',
        'icono' => 'ri-user-warning-line',
        'categoria' => 'Control',
        'tags' => ['regularizados', 'pendientes', 'empleados'],
        'activo' => false,
    ],
    [
        'nombre' => 'Ventas Sin Empleado',
        'descripcion' => 'Identifica ventas que necesitan asociacion o validacion de empleado.',
        'url' => '/ventas-sin-empleado',
        'icono' => 'ri-user-search-line',
        'categoria' => 'Control',
        'tags' => ['ventas', 'sin empleado', 'cedula', 'validacion'],
        'activo' => false,
    ],
];
