<?php

return [
    [
        'nombre' => 'Ventas por Usuario BET',
        'descripcion' => 'Consulta ventas por usuario en un mes seleccionado.',
        'url' => '/reportes-ventas-usuario-bet',
        'icono' => 'ri-user-search-line',
        'categoria' => 'Ventas',
        'tags' => ['usuarios', 'bet', 'ventas'],
        'activo' => true,
    ],
    [
        'nombre' => 'Faltantes BET',
        'descripcion' => 'Reporte de faltantes por usuario y agencia.',
        'url' => '/reportes-faltantes-bet',
        'icono' => 'ri-error-warning-line',
        'categoria' => 'Operaciones',
        'tags' => ['faltantes', 'bet', 'agencias'],
        'activo' => true,
    ],
    [
        'nombre' => 'Cuadre de Ventas',
        'descripcion' => 'Valida dias y montos procesados en ventas.',
        'url' => '/reportes-cuadre-ventas',
        'icono' => 'ri-calculator-line',
        'categoria' => 'Ventas',
        'tags' => ['cuadre', 'ventas', 'fechas'],
        'activo' => true,
    ],
    [
        'nombre' => 'Ventas por Agencia y Periodo',
        'descripcion' => 'Consulta ventas agrupadas por agencia en un rango de fechas.',
        'url' => '/reportes-ventas-agencia-periodo',
        'icono' => 'ri-calendar-check-line',
        'categoria' => 'Agencias',
        'tags' => ['agencia', 'periodo', 'ventas'],
        'activo' => true,
    ],
    [
        'nombre' => 'Ventas por Agencia',
        'descripcion' => 'Detalle de ventas filtrado por codigo de agencia.',
        'url' => '/reportes-ventas-por-agencia',
        'icono' => 'ri-store-2-line',
        'categoria' => 'Agencias',
        'tags' => ['agencia', 'ventas'],
        'activo' => true,
    ],
    [
        'nombre' => 'Ventas por Cedula',
        'descripcion' => 'Busca ventas asociadas a una cedula especifica.',
        'url' => '/reportes-ventas-por-cedula',
        'icono' => 'ri-id-card-line',
        'categoria' => 'Ventas',
        'tags' => ['cedula', 'ventas', 'usuarios'],
        'activo' => true,
    ],
    [
        'nombre' => 'Cruce de Usuarios',
        'descripcion' => 'Cruza usuarios entre sistemas y detecta diferencias.',
        'url' => '/reportes-cruce-usuarios',
        'icono' => 'ri-arrow-left-right-line',
        'categoria' => 'Auditoria',
        'tags' => ['cruce', 'usuarios', 'lotobet', 'lotonet'],
        'activo' => true,
    ],
    [
        'nombre' => 'Compensacion',
        'descripcion' => 'Consulta pagos a otra empresa y pagos por otra empresa por sistema.',
        'url' => '/reportes-compensacion',
        'icono' => 'ri-exchange-dollar-line',
        'categoria' => 'Finanza',
        'tags' => ['compensacion', 'finanza', 'pagos', 'lotobet', 'lotonet'],
        'activo' => true,
    ],
    [
        'nombre' => 'Verificador de Usuarios',
        'descripcion' => 'Verifica usuarios, faltantes y ventas relacionadas.',
        'url' => '/reportes-verificador-usuarios',
        'icono' => 'ri-shield-check-line',
        'categoria' => 'Auditoria',
        'tags' => ['verificador', 'usuarios', 'faltantes'],
        'activo' => true,
    ],
];
