<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    public $timestamps = false;
    protected $primaryKey = 'id';
    protected $fillable = [
        'companyid',
        'empleadoid',
        'nombres',
        'apellidos',
        'idposicion',
        'posicion',
        'salariomensual',
        'iddepto',
        'depto',
        'idciudad',
        'ciudad',
        'idpais',
        'pais',
        'ctabanco',
        'tipodocidentidad',
        'cedula',
        'sexo',
        'estadocivil',
        'nohijos',
        'direccion',
        'tel1',
        'tel2',
        'email',
        'profesion1',
        'profesion2',
        'fechanacimiento',
        'fechaingreso',
        'fechasalida',
        'iniciovacaciones',
        'finalvacaciones',
        'clienteid',
        'codigovendedor',
        'chofer',
        'bombero',
        'creadopor',
        'modificadopor',
        'fechagrabado',
        'fechamodificado',
        'atributoprn',
        'idsucursalturno',
        'moduloturno',
        'idturno',
        'nocalcularsalario',
        'turnorotativo',
        'porcientocomision',
        'enporciento',
        'cuenta',
        'cobrador',
        'mozo',
        'clavemozo',
        'lavador',
        'idsistemaviejo',
        'viapago',
        'idcentrocosto',
        'cuentanav',
        'idbanco',
        'viapago_banco',
        'idcalendario',
        'preaviso',
        'cesantia',
        'vacaciones',
        'navidad',
        'viapago_bancoemp',
        'tipocuenta',
        'cuentagastoinfotep',
        'cuentagastoriesgolaboral',
        'rutafoto',
        'enperiodo_prepost_natal',
        'en_licencia_medica',
        'tipo_empleado',
        'idplaza',
        'doctor'
    ];
}
